stages:
  - build
  - test
  - deploy

variables:
  # Define your environment variables here
  DATABASE_URL: "postgres://user:password@localhost:5432/dbname"
  API_KEY: "your_api_key"

before_script:
  # Set up any pre-requisites or environment configuration here
  - echo "Setting up environment..."

build:
  stage: build
  script:
    - echo "Building the application..."
    - npm install   # Example: Installing dependencies for a Node.js application
    - npm run build # Example: Building the application

test:
  stage: test
  script:
    - echo "Running tests..."
    - npm test      # Example: Running tests for a Node.js application

deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
    - ./deploy.sh   # Example: Running a deployment script
  only:
    - master # Deploy only when changes are pushed to the master branch

